export enum EDepartment {
  IT = 'Information Technology',
  ENGINEERING = 'Engineering',
  SALES = 'Sales',
  MARKETING = 'Marketing',
  FINANCE = 'Finance',
  HR = 'Human Resources',
  OPERATIONS = 'Operations',
  DESIGN = 'Design',
  HEALTHCARE = 'Healthcare',
  EDUCATION = 'Education',
  CUSTOMER_SERVICE = 'Customer Service',
  ADMINISTRATIVE = 'Administrative',
  LEGAL = 'Legal',
  CONSULTING = 'Consulting',
  MEDIA = 'Media',
  ARTS_ENTERTAINMENT = 'Arts & Entertainment',
  OTHER = 'Other',
}
